import type { Metadata } from "next";
import { ProfileProvider } from "./context/ProfileContext";
import { getProfile } from "@/app/action";

// import { Providers } from "@/core/provider/Provider";

export const metadata: Metadata = {
  title: "Profile Page",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo.png",
    shortcut: "/images/logo.png",
    apple: "/images/logo.png",
  },
};

export default async function ProfileLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ id: string }>;
}>) {
  const resolvedParams = await params;
  const data = await getProfile(resolvedParams.id);
  return <ProfileProvider value={data}>{children}</ProfileProvider>;
}
