import "./globals.css";

import logo from "@/public/images/logo.png";

import Footer from "@/components/layout/Footer";
import { LanguageProvider } from "@/core/context/LanguageContext";
import type { Metadata } from "next";
import { Instrument_Serif } from "next/font/google";
import Navigation from "@/components/layout/navigation/Navigation";
import ReduxProvider from "@/redux/Provider";
import { ThemeProvider } from "@/core/context/ThemeContext";

const instrumentSerif = Instrument_Serif({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-instrument-serif",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
  icons: {
    icon: logo.src,
    shortcut: logo.src,
    apple: logo.src,
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${instrumentSerif.variable}`}>
      <body>
        <ReduxProvider>
          <LanguageProvider>
            <ThemeProvider>
              <div className="flex flex-col min-h-screen">
                <Navigation />
                <main className="flex-1">{children}</main>
                <Footer />
              </div>
            </ThemeProvider>
          </LanguageProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
